ISSUE: 336: WIP: contact details in footer
ember-learn/ember-styleguide pull request #337
Opened 2020-08-29 13:15 UTC by fozy81

Work in progress for issue #336 (contact details in footer). Feedback welcome - just using this as a learning process. Note, github issue url uses component attribute not dynamically based on window.location - not sure best way to implement a dynamic match between window.location to github repo url. Github issue body 'camefrom=ember-website' could be improved.

2020-08-31 16:59 UTC, mansona requested changes
Thanks so much for taking this up, and so fast 😱  I've added a few suggestions, let me know if you have any questions 👍

2020-08-31 16:59 UTC, mansona commented on addon/templates/components/es-footer.hbs
> +  <EsFooterHelp @website="ember-website" />
my idea was to just pass in the `@contributeLink` that is already on the public API of the `<EsFooter />` component as it will already be pointing at a repo 👍

2020-08-31 16:59 UTC, mansona commented on addon/components/es-footer-help.js
> +export default class EsFooterHelpComponent extends Component {
we need to have a getter that will default to the ember-website if we don't have `args.contributeLink` available to us, something like: 

```javascript
get linkUrl() {
  return this.args.contributeLink || 'https://github.com/ember-learn/ember-website';
}
```

2020-08-31 16:59 UTC, mansona commented on addon/templates/components/es-footer-help.hbs
> +open an <a href="https://github.com/ember-learn/{{@website}}/issues/new?assignees=&template=general_issue.md&body=camefrom={{@website}}"> issue</a>,
I don't know that we need `assignees` or `template` in the URL (especially because we might not have the same issue templates in different repos) 🤔 

maybe we can get the basic implementation in place first without the custom body there because to be honest I have no idea how to achieve that 😂  it would be nice to get this released first and then we can iterate with the "nice to have" feature of a `cameFrom` URL, how does that sound?

2020-08-31 19:54 UTC, fozy81 commented on addon/templates/components/es-footer-help.hbs
> +open an <a href="https://github.com/ember-learn/{{@website}}/issues/new?assignees=&template=general_issue.md&body=camefrom={{@website}}"> issue</a>,
I've removed the template, assignee and cameFrom. Just opens a blank issue. I notice that github does points you towards the contributor guidelines if it's your first issue - so will give some pointers to first timers etc:
![image](https://user-images.githubusercontent.com/2878163/91760903-018b8d00-ebcc-11ea-98b2-2ff84388844f.png)

2020-08-31 19:54 UTC, fozy81 commented on addon/components/es-footer-help.js
> +export default class EsFooterHelpComponent extends Component {
I've added that in, working smoothly. :ok_hand:

2020-08-31 19:54 UTC, fozy81 commented on addon/templates/components/es-footer.hbs
> +  <EsFooterHelp @website="ember-website" />
I understand, that makes sense. I've updated to use @contributelink .

2020-08-31 20:03 UTC, fozy81 commented
@mansona Thanks for reviewing, I've made some changes. The email address is currently empty/placeholder, should this be an attribute too? :thinking:

2020-09-17 14:56 UTC, mansona commented on addon/templates/components/es-footer.hbs
> +  <EsFooterHelp />
```suggestion
  <EsFooterHelp @contributeLink={{@contributeLink}} />
```

2020-09-17 15:01 UTC, mansona commented on addon/templates/components/es-footer.hbs
> +  <EsFooterHelp />
actually I added this directly to the file because I wanted to update the example too to test something 😂

2020-09-17 15:01 UTC, mansona approved these changes
Great work! 🎉  I'm going to just check with @MelSumner to see if this meets the requirements and then we can get this merged and releases ASAP 💪 

Thanks again for the contribution

2020-09-17 15:04 UTC, mansona commented on addon/templates/components/es-footer-help.hbs
> +open an <a href="https://github.com/ember-learn/{{@website}}/issues/new?assignees=&template=general_issue.md&body=camefrom={{@website}}"> issue</a>,
Yes we can think about the template separately, really we should have a default template correctly setup on each of our repos 🙈 but that's a different issue 😂

2020-09-17 16:58 UTC, fozy81 commented
Thanks for the review @mansona let me know if any further changes required etc. Been great working on the ember-style addon -  really helped me understand how they work :bulb:  :brain:

2020-10-01 16:46 UTC, merged