fix .grid class column-count var taking precedence in safari
ember-learn/ember-styleguide pull request #356
Opened 2020-12-17 16:01 UTC by nickschot

In Safari it seems that in certain situations the `--column-count: 1;` from the .grid class takes precedence over the media query ones. As the responsive classes can't be used without the main .grid classes anyway this PR should prevent that from happening.

2021-03-18 07:14 UTC, ijlee2 commented
Hi, @nickschot. I think your pull request may unblock a PR in `ember-website`. Can you rebase your branch to see if the CI will pass?

2021-03-18 09:43 UTC, ijlee2 commented
@nickschot Thank you!

2021-03-18 09:47 UTC, mansona requested changes
Oh yes I forgot to comment on this when we discussed it in the Website Redesign meeting. I don't really know if this is the right solution 🤔 

If this is a safari bug I would like to have a bit more information on it before we commit this to the repo and add what seems like an unnecessary selector to the CSS

2021-03-18 09:58 UTC, nickschot commented
> Oh yes I forgot to comment on this when we discussed it in the Website Redesign meeting. I don't really know if this is the right solution 🤔
> 
> If this is a safari bug I would like to have a bit more information on it before we commit this to the repo and add what seems like an unnecessary selector to the CSS

We'll at the very least need to verify if the selectors appear in the correct order in the compiled CSS. But in my memory I think that was the case, hence why it was only happening in Safari for whatever reason.

2021-03-18 10:44 UTC, ijlee2 commented
It's happening in Chrome too: https://github.com/ember-learn/ember-website/issues/807

2021-03-18 21:54 UTC, mansona commented
@ijlee2 if it's really different with a trailing slash or not (omg 😱) then that is actually solved with a different fix in the website repo 👍

2021-03-25 18:00 UTC, mansona commented
As it turns out I didn't say what the "different fix" in the website repo website actually was 🙈  Now that https://github.com/ember-learn/ember-website/pull/809 is merged it should potentially be fixed

can we double check and see if its still a problem @nickschot ?

2021-04-29 15:14 UTC, jenweber commented
Notes from learning team meeting - this requires fixes upstream. Media queries with the same queries get squashed into one media query, and this reordering causes specificity problems.

2021-05-07 10:51 UTC, closed without merging