Updated links for ember-website
ember-learn/ember-styleguide pull request #377
Opened 2021-03-18 08:20 UTC by ijlee2

## Description

I updated the lists of links so that we can [remove the copy](https://github.com/ember-learn/ember-website/blob/74b259b11b76c7b1e6b5ace2a984bb41b4e77002/app/utils/header-links.js) in `ember-website`.

## How to Review

I recommend reviewing commits one by one.

In the first commit, I enabled Prettier to match the settings in `ember-website`. This allows us to review the differences in the lists in the second commit.

2021-03-18 11:08 UTC, mansona requested changes
I know you say to review this commit by commit but can we please keep the prettier and the actual link changes in different PRs to make sure that we don't miss things. 

For example, this PR adds a regression where the `/release/` part of the Guides link is being removed 👍

2021-03-18 11:09 UTC, mansona commented
also I'm surprised by the "remove the copy in the website" because this should never have been added to the website in the first place 🤔 

I can't find the PR where it was added, do you have the link?

2021-03-20 07:20 UTC, ijlee2 commented on addon/constants/links.js
> +      },
`https://guides.emberjs.com` is redirected to `https://guides.emberjs.com/release` and matches the pattern for API and CLI Guides below. The API and CLI links are redirected to the corresponding release pages. I don't think it's good to have a mix of patterns.

2021-03-25 17:43 UTC, mansona approved these changes

2021-03-25 17:44 UTC, locks commented
We discussed this PR at the meeting today and we are merging the formatting changes so we can proceed with updating the actual links :)
I updated the title to better reflect the content of the PR.

2021-03-25 17:44 UTC, merged