make sidebar wider to better match its contents' requirements
ember-learn/ember-styleguide pull request #382
Opened 2021-04-08 14:34 UTC by nickschot

The current width that was set a long time ago for the Blog implementation of the sidebar is not suitable for for example the guides. It also improves display of the sidebar in the Blog in case of long titles (e.g. ember times).

2021-04-10 20:16 UTC, mansona requested changes
Just 2 things to get to the bottom of before merging, maybe we can discuss at the weekly meeting on Thursday 👍

2021-04-10 20:16 UTC, mansona commented on addon/styles/sidebar-container.css
> +    width: 16rem;
so I don't mind changing the units from px to rem but I seem to remember that @pichfl said there was a reason we are using pixels for these things 🤔

Instead of having this PR get bogged down in a conversation about this can we keep it as pixels for now and if there is a reason to change to `rem` later then we can do that in a different PR. How does that sound?

2021-04-10 20:16 UTC, mansona commented on tests/integration/components/es-sidebar-test.js
> +      width: '684px',
This is implying that the content width is getting smaller, is that correct? 🤔 I think when we discussed this with @pichfl that we wanted to make the sidebar wider without making the content smaller. This is a super faint memory of a conversation though so let me know if you remember it differently

2021-04-15 07:58 UTC, nickschot commented on tests/integration/components/es-sidebar-test.js
> +      width: '684px',
That is correct, if we don't make the content smaller the entire website needs to be bigger. But both setups are within the range of "comfortable width to read" (even closer iirc) so I don't think it's really an issue.

2021-04-15 08:01 UTC, nickschot commented on addon/styles/sidebar-container.css
> +    width: 16rem;
There doesn't seem to be a standard in styleguide currently, we have mixed rem + px (e.g. --container-width is defined as 60something rem, some smaller things as px and most spacing things as rem. So.... I don't know? 😬

2021-04-15 10:53 UTC, pichfl commented on tests/integration/components/es-sidebar-test.js
> +      width: '684px',
We are talking about 22 pixels here. This is fine.

2021-04-15 10:54 UTC, pichfl approved these changes

2021-04-15 10:55 UTC, mansona commented on tests/integration/components/es-sidebar-test.js
> +      width: '684px',
👍  I'll resolve this one then

2021-04-15 10:57 UTC, mansona commented on addon/styles/sidebar-container.css
> +    width: 16rem;
I just chatted to @pichfl and he's happy with rem so we can get this merged 👍

2021-04-15 10:57 UTC, mansona approved these changes

2021-04-15 10:57 UTC, merged