Creates banner with the same style as on the current website
ember-learn/ember-styleguide pull request #419
Opened 2022-05-10 07:17 UTC by MinThaMie

Fixes #371

This implements the banner in the same way it's currently implemented on the website. The only difference is that the banner is **dismissible** on mobile. Because I thought it weird that that should not be the case.

<img width="689" alt="Screenshot 2022-05-10 at 09 13 28" src="https://user-images.githubusercontent.com/5811560/167571059-32284367-44bb-40ec-9ef6-e2a2aac61d78.png">

2022-05-11 14:17 UTC, jaredgalanis approved these changes
Thank you! 🎉

2022-05-11 14:20 UTC, jaredgalanis commented
@mansona I'm happy to have this merged as is. I don't think this work introduced the things that are making the checks fail. My sense is we can follow up with a PR that addresses those issues in a more targeted way. Does that sound okay to you?

2022-05-11 15:25 UTC, mansona requested changes
So I love this PR, but unfortunately the "dismiss" functionality opens a few too many cans of worms for now I think 🙈 

I have made a few suggestions to delegate the dismiss functionality to the parent application that calls this banner, but if you don't want to do that right now we could just simplify this component and remove the dismiss functionality and merge right away 👍

2022-05-11 15:25 UTC, mansona commented on addon/components/es-banner.js
> +  @tracked isShown = true;
I think if we're going to add the ability to dismiss the banner it might be good to pass that into the banner from outside 🤔  i.e. instead of calling `this.isShown` then we can call `@show` or something. That way the functionality is actually controlled by the caller to the component, does that make sense?

2022-05-11 15:25 UTC, mansona commented on addon/components/es-banner.hbs
> +    {{#if @dismissible}}
related to my other comment, if we're moving the `this.isShown` to an argument `@show` then we can show the close button if `@dismiss` is passed, and the `{{on "click" this.dismiss}}` would just delegate to `@dismiss` function. Does that make sense?

2022-05-12 13:05 UTC, MinThaMie commented
The current website does not use the dismiss property currently. So we could also completely remove the dismiss function and have it shown always :)

2022-05-13 12:29 UTC, mansona approved these changes
Looks great 🎉

2022-05-13 13:53 UTC, merged