Button group component
ember-learn/ember-styleguide pull request #423
Opened 2022-05-19 11:51 UTC by MinThaMie

Fixes #283 

This component warps their children in a div with some flex styling. I'm a bit in dubio if it should not be a more generic wrapper component because it could also work for this page: https://emberjs.com/teams/.

**Questions:**
- Should is be a more generic wrapper?
- Does it need the bottom margin?
- If we allow the `@centered` property do we want to change it to something that would support all the flex-alignments? Or is this something we could figure out somewhere else.

<img width="1638" alt="Screenshot 2022-05-19 at 13 47 32" src="https://user-images.githubusercontent.com/5811560/169286445-96f0de7f-3c19-4c56-9911-8ac8164c0459.png">

<img width="323" alt="Screenshot 2022-05-19 at 13 47 47" src="https://user-images.githubusercontent.com/5811560/169286440-72ec33ea-9087-4a4b-8c6b-27717292727e.png">

2022-05-20 01:44 UTC, jenweber commented on docs/components/buttongroup.md
> +# Button Group
I think the filename here should probably be `button-group` in order to be consistent in the nav menu with other two word components, like link-card

2022-05-20 01:46 UTC, MelSumner commented
For consideration: for links that look like buttons, adding support for the SPACE key can really help keyboard-only users.

2022-05-20 01:50 UTC, jenweber commented
A caveat with these comments is that I have not been very involved with the website work/styleguide lately. But here are my thoughts!

-  _Should is be a more generic wrapper?_ No, I think it's fine for it to have one job
-   _The name button-group might be confusing for other people because it often means (e.g. Bootstrap) that the buttons will touch each other._ I like the name you chose. I have seen this same name in other component frameworks besides bootstrap, with the buttons not touching  
-   _Does it need the bottom margin?_ No, because when we use these components in the apps, we can use the spacing helpers. See https://deploy-preview-423--ember-styleguide.netlify.app/css/helpers/#spacinghelpers
-  _If we allow the @centered property do we want to change it to something that would support all the flex-alignments? Or is this something we could figure out somewhere else._ I suggest looking at the use cases we need to support. Probably we don't need anything fancy and centered will be enough. But I'm not sure.

Before merging, I recommend removing the margin and renaming that one file. Otherwise this looks good to go, from my perspective.

2022-05-20 01:51 UTC, jenweber commented
P.S. to just say it directly, I think my review alone is probably not enough and someone who has been more active in this project should also take a look!

2022-05-20 07:37 UTC, MinThaMie commented
> For consideration: for links that look like buttons, adding support for the SPACE key can really help keyboard-only users.

I think this should be part of a separate issue that actually does something with buttons instead of putting it in this one with the wrapper Classe

2022-05-20 07:39 UTC, MinThaMie commented on docs/components/buttongroup.md
> +# Button Group
You're correct :)

2022-05-24 13:36 UTC, jaredgalanis approved these changes
This looks good to me 👍

2022-07-15 17:01 UTC, mansona requested changes
Hey folks sorry about not getting back to y'all on this one. We discussed this in the website redesign meeting and essentially it would make more sense that this was implemented as a CSS helper rather than a component. One of the philosophies of this new redesign implementation is that we should use the platform as much as possible, and when I discussed this with @MinThaMie it's clear that converting this to a CSS helper would even make it more useful in other places 🎉

2022-07-21 08:58 UTC, mansona approved these changes
This looks great 😍 thanks for making this change! much better 🎉

2022-07-21 09:06 UTC, merged